### ISSUE TITLE
[Bug]: App Icon Incorrect Sizing

### ISSUE THREAD

**Issue by MarkBeharrell** [ciderapp/Sabiiro-BugTracker#121] opened 2023-04-05 09:57 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

This week via Windows Store

### Operating System Version

Windows 11 22H2

### Describe the Bug

Main Windows icon appears to be either the wrong size or quality.

![2023-04-05 (2)](https://user-images.githubusercontent.com/20297618/230047581-9053a6df-3ad9-4f1d-a857-a9552095973b.png)

### Steps to Reproduce

Installed the update via Windows Store this week. 

### Build timestamp

1680688423277

**Comment by coredev-uk** [comment] 2023-04-10 19:12
Duplicate of #118

**Closed by coredev-uk** 2023-04-10 19:12 UTC
Labels: 🐛 Bug, 🛠️ Triaged, ⚙️ Backend, 📌 Inconsistency / Nitpicking
