### ISSUE TITLE
[Bug]:there is no reaction when clicking like button of any song

### ISSUE THREAD

**Issue by chemzi** [ciderapp/Sabiiro-BugTracker#225] opened 2023-05-31 14:48 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue.

### What operating system are you using?

Windows

### Build Details

2.0.3

### Operating System Version

Windows11 cider2 Microsoft store

### Describe the Bug

there is no reaction when clicking like button of any song

### Steps to Reproduce

click like button

### Anything else?

<img width="196" alt="2023-05-31_22-46-33" src="https://github.com/ciderapp/Sabiiro-BugTracker/assets/130055703/9db9c6b4-b7a9-428d-89d2-c208e0874f94">

### Connect Device ID

cider2 store version2.0.3

### Build timestamp

1685544228651

**Comment by coredev-uk** [comment] 2023-06-01 17:33
Duplicate of #161

**Closed by coredev-uk** 2023-06-01 17:33 UTC
Labels: 🐛 Bug
