### ISSUE TITLE
[Bug]: Is there a "Close Button Should Hide the App" option for Cider 2 preview (Windows version)? 

### ISSUE THREAD

**Issue by XinranZhao** [ciderapp/Sabiiro-BugTracker#204] opened 2023-05-17 01:48 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Cider 2 Preview, Microsoft Store
Built on 5/2/2023, 11:00:53 AM | Quasar v2.11.10

### Operating System Version

Windows 10

### Describe the Bug

Is there an "Close Button Should Hide the App" option for Windows version? I use Cider on my Linux machine before and love it. Today I purchased Cider 2 Preview on my Windows 10 laptop to replace iTunes. However, I didn't find the "Close Button Should Hide the App" option. This is the most useful feature for me, largely the reason why I buy it, because with iTunes I always accidentally pressure Close button, which closes the App. Did I miss it somewhere? Please don't kill it in the Windows version, I don't understand why. 

### Steps to Reproduce

Always

**Comment by coredev-uk** [comment] 2023-06-01 16:20
Duplicate of #191

**Closed by coredev-uk** 2023-06-01 16:20 UTC
Labels: 🐛 Bug
