### ISSUE TITLE
[Bug]: Randomly Pausing momentarily at 13 second left mark

### ISSUE THREAD

**Issue by Ravioliii** [ciderapp/Sabiiro-BugTracker#173] opened 2023-05-03 00:25 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Cider 2.02 MS store AND discord previews 

### Operating System Version

Windows 11 22H2

### Describe the Bug

Very consistent freezing of song just after the 15 second mark of any song. It can happen very frequently.  

### Steps to Reproduce

1. Play a song 
2. Wait until 15 seconds left of song
3. Freeze happens at 13 seconds
or
1. Play a song
2. Skip to just before the 15 second mark
3. Freeze happens at 13 seconds 

### Anything else?

All my content restrictions are off. This is not just an issue with the most recent builds. I've had this issue for a couple of months with multiple builds. Not sure if it was a change of the backend that started it or not. 

Rewinding the song back and letting it play to the 13 second mark does not produce the bug. Switching the song will produce the bug again.

https://user-images.githubusercontent.com/38828794/235812328-d0664530-4633-4bc8-bcac-e65e05824960.mp4

### Connect Device ID

2RFWuSwWUnnB3YIin1jb

### Build timestamp

1683072022058

**Comment by d3rpp** [comment] 2023-05-04 22:08
aight, been able to reproduce this issue

only happens when i run docker compose build on a project causing high CPU usage

so literally a skill issue on your computer ig.

no clue what's causing it

**Comment by cryptofyre** [comment] 2023-05-04 22:24
thread priority

**Comment by d3rpp** [comment] 2023-05-04 22:30
that could be it.

since this issue is really spotty and inconsistent i'll close this issue for now, but it could be reopened if thread priority turns out to nor be the case.

**Closed by d3rpp** 2023-05-04 22:30 UTC
Labels: 🐛 Bug, 🙋‍♂️ Help wanted, 🖥️ Frontend

**Comment by AstroKosmoNaut** [comment] 2023-08-18 10:30
I can confirm this also happens on:

Athlon II X4 640 4 code 3GHz, 8GB memory, Asus Xonar DX card, Multiboot:
Windows 10 22H2
Ubuntu 22.04 LTS
As far as I can tell, there a no CPU issues here.

HP Elitebook 2560P, Intel Core i5-2540M, 4GB memory:
Ubuntu 18.04 LTS

 On my systems, the bug is consistent. Let me know if I can do anything to help.
