### ISSUE TITLE
[Bug]: The background of the application becomes white for no reason.

### ISSUE THREAD

**Issue by StudentIITU** [ciderapp/Sabiiro-BugTracker#207] opened 2023-05-18 16:36 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

I have downloaded it today

### Operating System Version

Windows 11 version 22H2

### Describe the Bug

The black background of the application suddenly becomes white if I select it from the list of running applications. The bug does not appear immediately, but after several times choosing an application. After that, I have to restart the application to get it back to normal
I don't know what the cause of this error is.
![image_2023-05-18_22-29-42](https://github.com/ciderapp/Sabiiro-BugTracker/assets/96124721/2ebdd115-7e0a-4102-9863-03e8e2f3a08c)

### Steps to Reproduce

1. I was just selecting a tab with an application icon, and once in a while it might show up.
I don't know how often I have to reopen the application tab for the error to appear.

### Anything else?

Just this bug.

**Comment by aitbw** [comment] 2023-05-19 18:45
I've been affected by this bug as well ever since I got Cider (Preview) on March 24th, Windows 11 Home (21H2)

Currently running Cider 2.0.3 (v1.1.7.0, acc. to the Microsoft Store)

**Comment by cryptofyre** [comment] 2023-05-19 18:45
We're investigating the issue! Thanks for the feedback.

**Comment by coredev-uk** [comment] 2023-06-01 16:22
Duplicate of #174

**Closed by coredev-uk** 2023-06-01 16:22 UTC
Labels: 🐛 Bug
