### ISSUE TITLE
[Bug]: can't  sign in after sign out

### ISSUE THREAD

**Issue by Dugar111** [ciderapp/Sabiiro-BugTracker#171] opened 2023-05-02 07:05 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

About ten days ago

### Operating System Version

windows 10 pro

### Describe the Bug

Can't  sign in after sin out my apple muisc account. I press sign into apple music button. But white blank window show up and not sign in window

### Steps to Reproduce

i can't  do much please fix this problerm fast

### Anything else?

![image](https://user-images.githubusercontent.com/132335607/235600767-049bc1ea-e970-4097-a9d5-23f40f1b487a.png)

### Connect Device ID

1.1.3.0

### Build timestamp

1683010659271

**Comment by coredev-uk** [comment] 2023-05-02 07:27
Please check for existing issues before opening a new one.
duplicate of #170

**Closed by coredev-uk** 2023-05-02 07:27 UTC
Labels: 🐛 Bug
