### ISSUE TITLE
[Bug]: Search not working as intended

### ISSUE THREAD

**Issue by FreSingh** [ciderapp/Sabiiro-BugTracker#31] opened 2023-03-07 08:09 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 11

### Describe the Bug

Doesnt search query when directly clicking and going to the search section, gets fixed when you get to the listen now tab and then try searching

### Steps to Reproduce

Search anything after the first search upon launching

**Comment by coredev-uk** [comment] 2023-04-23 10:09
I cannot reproduce this issue in the latest build, closing.

**Closed by coredev-uk** 2023-04-23 10:09 UTC
Labels: 🐛 Bug, 🛠️ Triaged, 🖥️ Frontend, 🗄️ Could not reproduce
