### ISSUE TITLE
[Bug]: Saki AI not functioning on Cider (2/EA/Preview) 

### ISSUE THREAD

**Issue by Rauf321X** [ciderapp/Sabiiro-BugTracker#168] opened 2023-04-30 22:59 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

N/A

### Operating System Version

Windows 10 Pro Version 21H2 

### Describe the Bug

When using Saki AI, after sending a prompt, Saki fails to function and instead gives an error message saying "Sorry, I can't have a conversation right now. Please try again later." followed by "In the meantime, you can try out our search feature to find music. We know that we have at least 500 songs in our library."

This has continued to happen on both of my Windows devices, one running Windows 11 and this device, running Windows 10 21H2. I've reproduced this issue on both devices across many networks. It seems to be an issue with its connection to the OpenAI API? This issue can happen when an API key is invalidated (made another API key, one expired, etc.) and that seems to be a possible issue. 

Here's what I got: 
![image](https://user-images.githubusercontent.com/108030099/235379381-5d0a21eb-d071-43d5-b734-b959ad9a0b0b.png)

### Steps to Reproduce

1. Opened Cider (Preview/2/EA) on my Windows device.
2. Use the Saki AI button at the top search bar. 
3. Type any message after the Saki AI prompt saying "How can I assist you with your music needs today?" 
4. Saki AI will respond with that error. 

### Anything else?

Here's the information of my device and the build of Cider I'm using along with some other info to help clear things up:

- Cider Build Info 
![image](https://user-images.githubusercontent.com/108030099/235379792-598a97c8-4141-4aa9-8489-8113a898350d.png)
![image](https://user-images.githubusercontent.com/108030099/235379821-fbb6400c-8a7c-496c-9edf-3526786ba0dc.png)
- Windows Info
![image](https://user-images.githubusercontent.com/108030099/235379841-f27f0ceb-c53a-4d6a-b4b4-3253215c741f.png)
(I don't have my Windows 11 PC near me at the moment, so that'll come later) 

### Build timestamp

1682891632429

**Comment by coredev-uk** [comment] 2023-04-30 23:09
Please check existing issues before opening an issue. This feature is clearly placed in Advanced settings and is in testing. 

Duplicate of #158

**Closed by coredev-uk** 2023-04-30 23:09 UTC
Labels: 🐛 Bug
