### ISSUE TITLE
[Bug]: Not adding to the top in recently added the albums that exist in your library when you add a new song from it

### ISSUE THREAD

**Issue by franolzak** [ciderapp/Sabiiro-BugTracker#208] opened 2023-05-18 19:11 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Today

### Operating System Version

Windows11

### Describe the Bug

[Bug]: Not adding to the top in recently added the albums that exist in your library when you add a new song from it

### Steps to Reproduce

I added new song from album that was in my library
it didnt added to the top of recently added

**Comment by kobaltkloud** [comment] 2023-05-21 06:56
Similar problem on my issue #29

**Comment by coredev-uk** [comment] 2023-06-01 16:11
Duplicate of #29

**Closed by coredev-uk** 2023-06-01 16:11 UTC
Labels: 🐛 Bug
