### ISSUE TITLE
[Bug]: Unable to sign in or connect to Apple Music

### ISSUE THREAD

**Issue by research-drive-117** [ciderapp/Sabiiro-BugTracker#202] opened 2023-05-15 18:13 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Version 2.0.2 - Installed on 13/05/2023

### Operating System Version

Windows 10 Pro 19045.2913

### Describe the Bug

Unable to sign in or connect to Apple Music. Sign in page issues error stating 'Problem Connecting. There may be a network issue.' 

I am able to access Apple Music through iTunes from the same WIndows 10 device, so apparently it is not a network issue ! 

### Steps to Reproduce

1. Closed and reopened Cider
2. I disconnected and reconnected from my internet connection. 
3. Restarted device 

### Build timestamp

1684173959273

**Comment by ChrisAtchison** [comment] 2023-05-16 22:45
I'm having the same issue on Windows 11 22H2, though I'm still able to listen to and save albums which syncs to my phone despite the failure

**Comment by coredev-uk** [comment] 2023-06-01 16:19
Duplicate of #197

**Closed by coredev-uk** 2023-06-01 16:19 UTC
Labels: 🐛 Bug
