### ISSUE TITLE
[Bug]: Out of Memory

### ISSUE THREAD

**Issue by Denyce** [ciderapp/Sabiiro-BugTracker#122] opened 2023-04-07 13:11 UTC
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Sabiiro-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Build Details

Cider 2 (Preview)

### Operating System Version

Windows 11 Pro 22621.1413

### Describe the Bug

After a few seconds, the app "crashes" with the error code "Out of Memory".
<img width="1027" alt="cider2" src="https://user-images.githubusercontent.com/4258665/230612901-fd048c13-f84c-433e-9308-537a32f9c4c8.png">

I have already repaired the app via windows app functionality. Without success. I have also completely uninstalled and reinstalled the app. Also without success.  

### Steps to Reproduce

1. Install the app. 
2. Lounch the app
3. Login to Apple Music (Germany)
4. After a few seconds, the app will show the Image in the descriped Bug.

### Anything else?

I buyed the app at the 3rd of April. At this day the app works fine for me. 
On the 6th of April i tryed to open the app using the taskbar icon. Nothing happend.
I startet the app via windows start menu. 
The app starts from the beginning like a new installation and prompted me to login to apple music. Since then the app no longer works. 

**I think the app crashes loding the apple music mediathek.** 
I have simmilar issue with the Apple Music Preview app...  

### Build timestamp

1680871737905

**Comment by CandiceJoy** [comment] 2023-04-10 05:29
Can confirm.  Seeing this on Win 11 Enterprise.  I have 64gb of RAM :P

**Comment by steffenlongva** [comment] 2023-04-10 10:03
Also having same issue, Win 11, 64gb of RAM

**Comment by coredev-uk** [comment] 2023-04-10 19:02
This should not be occurring on latest build (09/04). Please make sure you update your clients where possible. As for Microsoft Store, I'm not entirely sure which build that is using.

**Comment by coredev-uk** [comment] 2023-04-10 19:02
Duplicate of #65

**Closed by coredev-uk** 2023-04-10 19:02 UTC
Labels: 🐛 Bug

**Comment by d3rpp** [comment] 2023-04-11 03:46
A Fix for this issue has been submitted to the microsoft store, just awaiting approval from microsoft
